# Default values for fluentbit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fluentbitOperatorImage:
  repository: "kubesphere/fluentbit-operator"
  tag: "v0.7.0"

fluentbit:
  image: "kubespheredev/fluent-bit"
  tag: "v1.7.3"



imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

deployment:
  volunmes:
    image:
      repository: "docker"
      tag: "19.03"


#podAnnotations: {}

## if want to deploy CRDs used by fluentbit Operator.
##createCustomResource: false

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



resources:
  # fluentbit resources. If you do want to specify resources, adjust them as necessary
  fluentbit:
  # Fluent Bit resources. User can adjust it based on the log volume.
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 25Mi

  operator:
  # FluentBit operator resources. Usually user needn't to adjust these.
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 20Mi

output:
  #Configure the output plugin parameter in FluentBit.
  #You can set enable to true to output logs to the specified location.
  es:
    enable: false
    host: "<Elasticsearch url like elasticsearch-logging-data.kubesphere-logging-system.svc>"
    port: 9200
  forward:
    enable: false
    host: "<fluentd url like fluentd.kubesphere-logging-system.svc>"
    port: 24224
  kafka:
    enable: false
    brokers: "<kafka broker list like xxx.xxx.xxx.xxx:9092,yyy.yyy.yyy.yyy:9092>"

nodeSelector: {}

tolerations: []

affinity: {}
