apiVersion: v2
name: fluent-operator
description: Fluent Operator provides great flexibility in building a logging layer based on Fluent Bit and Fluentd.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - operator
version: 4.0.0-rc1
# renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator
appVersion: "3.5.0"
icon: https://raw.githubusercontent.com/fluent/fluent-operator/master/docs/images/fluent-operator-icon.svg
home: https://www.fluentd.org/
sources:
  - https://github.com/fluent/fluent-operator
maintainers:
  - name: wenchajun
    email: dehaocheng@kubesphere.io
  - name: marcofranssen
    email: marco.franssen@gmail.com
    url: https://marcofranssen.nl
  - name: joshuabaird
    email: joshbaird@gmail.com
dependencies:
  - name: fluent-bit-crds
    repository: "file://../charts/fluent-bit-crds" #  set to remote repository during release by CI
    version: 0.1.0
    condition: fluentbit.enable && fluentbit.crdsEnable
  - name: fluentd-crds
    repository: "file://../charts/fluentd-crds" #  set to remote repository during release by CI
    condition: fluentd.enable && fluentd.crdsEnable
    version: 0.1.0
