apiVersion: v2
name: fluent-operator
description: Fluent Operator provides great flexibility in building a logging layer based on Fluent Bit and Fluentd.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - operator
version: 3.3.0
# renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator
appVersion: "3.4.0"
icon: https://raw.githubusercontent.com/fluent/fluent-operator/master/docs/images/fluent-operator-icon.svg
home: https://www.fluentd.org/
sources:
  - https://github.com/fluent/fluent-operator
maintainers:
  - name: wenchajun
    email: dehaocheng@kubesphere.io
dependencies:
  - name: fluent-bit-crds
    repository: "file://charts/fluent-bit-crds"
    version: 3.3.0
    condition: fluentbit.crdsEnable
  - name: fluentd-crds
    repository: "file://charts/fluentd-crds"
    version: 3.3.0
    condition: fluentd.crdsEnable
