apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.3.7
spec:
  image: kubespheredev/fluent-bit:v1.3.7
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluent-bit-config
  tolerations:
    - operator: Exists
