apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fluentbit-fluentBit.yaml
- fluentbitconfig-fluentBitConfig.yaml
- input-tail.yaml
- input-systemd-docker.yaml
- input-systemd-kubelet.yaml
- filter-kubernetes.yaml
- filter-systemd.yaml
- output-elasticsearch.yaml
- output-forward.yaml
- output-kafka.yaml
- filter-containerd.yaml
- fluentbit-containerd-config.yaml
- systemd-lua-config.yaml

# Change to the namespace you want such as: 
# namespace: fluent