image:
  repository: dockerhub.qingcloud.com/kslogging/fluentbit-operator
  tag: latest
  pullPolicy: Always

# Namespace to watch fot FluentBit CRD
watchNamespace: "kubesphere-logging-system"

affinity: {}
  # key: value
tolerations: []
# - key: "key"
#   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

rbac:
  enabled: true

tls:
  enabled: false
  secretName: ""
  sharedKey: ""

fluentbit:
  enabled: true
  namespace: "kubesphere-logging-system"
  image: dockerhub.qingcloud.com/kslogging/fluent-bit:1.0.5

configmap-reloadï¼š
  image: dockerhub.qingcloud.com/kslogging/configmap-reload:latest
