{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
  {{- if .Values.fluentbit.imagePullSecrets }}
  imagePullSecrets:
{{ toYaml .Values.fluentbit.imagePullSecrets | indent 4 }}
  {{- end }}
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
{{- toYaml .Values.fluentbit.resources | nindent 4  }}
  fluentBitConfigName: fluent-bit-config
  {{- if .Values.fluentbit.namespaceFluentBitCfgSelector }}
  namespaceFluentBitCfgSelector:
{{ toYaml .Values.fluentbit.namespaceFluentBitCfgSelector | indent 4  }}
  {{- end }}
{{- if .Values.fluentbit.envVars }}
  envVars:
{{ toYaml .Values.fluentbit.envVars | indent 4 }}
{{- end }}
{{- with .Values.fluentbit.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.fluentbit.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.fluentbit.priorityClassName }}
  priorityClassName: {{ .Values.fluentbit.priorityClassName | quote }}
{{- end }}
  {{- with .Values.fluentbit.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.schedulerName }}
  schedulerName: {{ .Values.fluentbit.schedulerName }}
  {{- end }}
  {{- if .Values.fluentbit.secrets }}
  secrets:
{{ toYaml .Values.fluentbit.secrets | indent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.additionalVolumes }}
  volumes:
{{ toYaml .Values.fluentbit.additionalVolumes | indent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.additionalVolumesMounts }}
  volumesMounts:
{{ toYaml .Values.fluentbit.additionalVolumesMounts | indent 4 }}
  {{- end }}
  {{- if or .Values.fluentbit.annotations .Values.fluentbit.output.stdout.enable }}
  annotations:
  {{- with .Values.fluentbit.annotations }}
{{ toYaml . | indent 4 }}
  {{- end -}}
  {{- if .Values.fluentbit.output.stdout.enable }}
    fluentbit.io/exclude: "true"
  {{- end }}
  {{- end }}
  {{- if .Values.fluentbit.labels }}
  labels:
{{ toYaml .Values.fluentbit.labels | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}