{{- if .Values.fluentbit.kubeedge.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config-edge
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    parsersFile: parsers.conf
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
{{- end }}