{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  {{- if .Values.fluentbit.namespaceClusterFbCfg }}
  namespace: {{ .Values.fluentbit.namespaceClusterFbCfg }}
  {{- end }}
  configFileFormat: {{ .Values.fluentbit.configFileFormat | default "classic" }}
  service:
    parsersFiles:
      - /fluent-bit/etc/parsers.conf
      - /fluent-bit/config/parsers_multiline.conf
    httpServer: true
  {{- if .Values.fluentbit.logLevel }}
    logLevel: {{ .Values.fluentbit.logLevel }}
    {{- end }}
{{- if .Values.fluentbit.service.storage }}
    storage:
{{ toYaml .Values.fluentbit.service.storage | indent 6 }}
{{- end }}
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  parserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  multilineParserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
{{- end }}
{{- end }}
