{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.filter.containerd.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: containerd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.*
  filters:
  - lua:
      script:
        key: containerd.lua
        name: fluent-bit-containerd-config
      call: containerd
      timeAsTable: true
{{- end }}
{{- end }}
