{{- if .Values.fluentbit.kubeedge.enable }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config-edge
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  configFileFormat: {{ .Values.fluentbit.configFileFormat | default "classic" | quote }}
  service:
    parsersFile: parsers.conf
    {{- with .Values.fluentbit.service.schedulerBase }}
    schedulerBase: {{ . }}
    {{- end }}
    {{- with .Values.fluentbit.service.schedulerCap }}
    schedulerCap: {{ . }}
    {{- end }}
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
  parserSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
      node-role.kubernetes.io/edge: "true"
{{- end }}
