{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
{{- if .Values.fluentd.output.es.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-es
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - elasticsearch:
        host: {{ .Values.fluentd.output.es.host }}
        port: {{ .Values.fluentd.output.es.port }}
        logstashFormat: true
        logstashPrefix: {{ .Values.fluentd.output.es.logstashPrefix }}
      {{- if .Values.fluentd.output.es.buffer }}
      buffer:
        type: {{ .Values.fluentd.output.es.buffer.type }}
        path: {{ .Values.fluentd.output.es.buffer.path }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
