apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluentbit-sample
  labels:
    app: fluent-bit
spec:
  # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-bit
  image: ghcr.io/fluent/fluent-operator/fluent-bit:4.0.9
  imagePullPolicy: IfNotPresent
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  fluentBitConfigName: fluentbitconfig-sample
  disableLogVolumes: false
