apiVersion: logging.kubesphere.io/v1alpha1
kind: FluentBitConfig
metadata:
  name: fluentbitconfig-sample
spec:
  service:
    flush: 1
    daemon: false
    logLevel: info
    parsersFile: parsers.conf
  inputSelector:
    matchExpressions:
    - key: logging.kubesphere.io/enabled
      operator: In
      values: ["true"]
  filterSelector:
    matchExpressions:
    - key: logging.kubesphere.io/enabled
      operator: In
      values: ["true"]
  outputSelector:
    matchExpressions:
    - key: logging.kubesphere.io/enabled
      operator: In
      values: ["true"]
