apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd-forward
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
    - type: forward
      forward: 
        bind: 0.0.0.0
        port: 24224
  replicas: 1
  image: zhu733756/fluentd:config-reloader
  fluentdCfgSelector: 
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
   
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: fluentd-config
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces: 
    - kube-system
    - kubesphere-logging-system
    - kubesphere-monitoring-system
  outputSelector:
    matchLabels:
      output.fluentd.fluent.io/enabled: "true"

---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-stdout
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
    - type: elasticsearch
      elasticsearch:
        host: elasticsearch-logging-data.kubesphere-logging-system.svc
        port: 9200
        logstashFormat: true
        logstashPrefix: ks-logstash-log