apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: fluentbit-operator
  name: kubesphere:operator:fluentbit-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesphere:operator:fluentbit-operator
subjects:
- kind: ServiceAccount
  name: fluentbit-operator
  namespace: kubesphere-logging-system
