apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: auditd-input
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  tail:
    tag: auditd
    path: /var/log/audit/audit.log
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    db: /fluent-bit/tail/auditd.db
    dbSync: Normal
