name: Renovate
on:
  push:
    paths:
      - ".github/workflows/renovate.yaml"
      - ".github/renovate-config.js"
  schedule:
    - cron: "0 7 * * 5"
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@957af03d760b2c87fc65cb95628f6d5f95d9c578 # v46.0.0
        with:
          configurationFile: ".github/renovate-config.js"
          token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          LOG_LEVEL: ${{ env.ACTIONS_STEP_DEBUG == 'true' && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: ${{ steps.app-token.outputs.token }}
          RENOVATE_ALLOW_SCRIPTS: true
          RENOVATE_SEPARATE_MAJOR_MINOR: false
