name: Renovate
on:
  push:
    paths:
      - ".github/workflows/renovate.yaml"
      - ".github/renovate-config.js"
  schedule:
    - cron: "0 7 * * 5"
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5712c6a41dea6cdf32c72d92a763bd417e6606aa # v44.0.5
        with:
          configurationFile: ".github/renovate-config.js"
          token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          LOG_LEVEL: ${{ env.ACTIONS_STEP_DEBUG == 'true' && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: ${{ steps.app-token.outputs.token }}
          RENOVATE_ALLOW_SCRIPTS: true
          RENOVATE_SEPARATE_MAJOR_MINOR: false
